### ISSUE TITLE
Python3 Ubuntu 18.10

### ISSUE THREAD

**Issue by m1st0** [JSubelj/g910-gkey-macro-support#3]
**Description**
Some of the code does not work due to relying on env paths linking to Python2 instead of Python3.

**To Reproduce**
1. Running installer.sh results in errors on my system since _/usr/bin/python_ is symlinked to _/usr/bin/python2.7_
2. Other files such as setup.py cannot complete correctly because _#!/usr/bin/env python_ relates to Python2.
3. Although my install prefix may be different from another person's setup, files like _/usr/local/lib/python3.6/dist-packages/g910_gkey_macro_support-0.1.0-py3.6.egg/cli_entry_point.py_ cannot operate due to similar links to Python2 instead of Python3.

**Expected behavior**
Libraries and environment should depend on Python 3.6 as requested.

**Desktop (please complete the following information):**
 - Ubuntu Cosmic 18.10
 - 4.18.0-13
 - KDE
 - g910-gkeys version: from PKG_INFO 0.1.0
 - Python symlinks to 2.7.15+ vs 3.6.7

**Additional context**
- I can fix all errors switching all necessary files to _#!/usr/bin/env python3_ and any direct python calls to _python3_ .  This understandably may not be general but useful for Ubuntu after 18.04 due to [dependencies](https://askubuntu.com/questions/1065572/how-to-safely-switch-to-python3-as-default-after-upgrade-to-ubuntu-18-04).
- Note that I can also solve this issue by [updating alternative references](https://unix.stackexchange.com/questions/410579/change-the-python3-default-version-in-ubuntu), however this may cause system-wide issues for Python2.
- I wanted to discuss the preferred path to move forward before I switch the code base to rely specifically on Python3 before providing a pull-request of changes.

**Comment by JSubelj** [comment]
Hey,

first of all thank you for trying to use my driver.

Now as I can tell you are having problems because your python is not symlinked to python3.7. Have you tried manually running steps with python3, like `python3 setup.py install` and so on? Also did you tried running /usr/bin/g910-gkeys as: `sudo python3 /usr/bin/g910-gkeys`? I think that changing shabangs is not required, all you need to do is change line 6 in g910-gkeys.service to: `ExecStart=python3 /usr/bin/g910-gkeys`.

I don't completly understand the implication that the driver is using python2. Can you explain a bit further. Also can I see some errors that you are having problems with.

Thanks for your cooperation and sorry for a late response.

**Comment by JSubelj** [comment]
Maybe also this issue will be helpful to you: https://github.com/JSubelj/g910-gkey-macro-support/issues/5
