### ISSUE TITLE
[Question] What is "keyboard_mapping" ?

### ISSUE THREAD

**Issue by braoult** [JSubelj/g910-gkey-macro-support#41]
I wonder what is "keyboard_mapping" used for. I tried with "si" on my qwerty/us keyboard, and everything is working fine. Is this setting really necessary ?
If not, it would allow any G910 user to use the driver, without fear...

**Comment by suabo** [comment]
If you just use hotkey_type run or python the keyboard_mapping doesn't matter. But if you use a shortcut or typeout it won't work as excepted because the keys are on different positions in different keyboard layouts. Just look up a german keyboard on google. You see almost all letters are identical except y and z are flipped. But when it comes to special chars there is nothing the same. This is alsmost for every country/language the case since they use different letters or signs more often then others.

I will add this info on the next chance to the readme.
