### ISSUE TITLE
usb dev: not found. retrying

### ISSUE THREAD

**Issue by PanagiotisGts** [JSubelj/g910-gkey-macro-support#7]
Hello,
After following your instructions to install your package and ensuring uinput is already installed,
under the log file ( /var/log/g910-gkeys.log )  there is an endless amount of :

2019-01-22 13:15:56,866 [DEBUG] {lib.keyboard_initialization.usb_and_keyboard_device_init} - usb dev: not found. retrying

The test macro key under G1 is not functioning, although using g810-led --list-keyboards correctly returns my G910 keyboard information.

Under Manjaro, kernel 4.19.14

**Comment by JSubelj** [comment]
First thank you for using my software.

This can sometimes happen if you run the driver when some other program already locked onto the keyboard. Have you tried restarting the service/enabling the service and restarting the computer?

**Comment by qqpanos** [comment]
Thanks for your reply.
Tried all of the above mentions but still no luck on getting macros to work. Systemctl status displays it as active since boot but showkey -a only registers macro presses when keys are mapped to F* keys. Also, during bootup keyboard gets disconnected ~4 times before finally becoming available. Will test this on another computer running stock Arch to see if it works properly.

**Comment by JSubelj** [comment]
Afaik macros don't get registered by showkey, because they are not normal keys and their signal does not correspond to any known key. Do you still get same usb dev: not found messages?  If so then maybe your keyboard does not have the same product id (or maybe even vendor id). Currently this two variables are set to:
```
USB_VENDOR = 0x046d
USB_PRODUCT = 0xc335
```
The 4 time disconnect is a known issue caused by g810-led it is described here: https://github.com/MatMoul/g810-led/blob/master/INSTALL.md#boot-profiles-

**Comment by qqpanos** [comment]
Managed to get it working with your USB_VENDOR and USB_PRODUCT variables. Dug into the python files and changed them and rebuilt it. Works like a charm now! Thank you very much for your help and for your software!

**Comment by JSubelj** [comment]
Glad I can be of help! Can you please share your USB_VENDOR and USB_PRODUCT variables and where you found them so I can add the data to wiki for troubleshooting.

**Comment by PanagiotisGts** [comment]
I think it's the Spark, the first generation.
```
My product Information :
USB_VENDOR = 0x046d
USB_PRODUCT = 0x0c32b
```
To get your keyboard specific info execute  ` g910-led --print-device ` . The variables are initialized on the file ` /build/lib/lib/keyboard_initialization/usb_and_keyboard_device_init.py `

Glad I was able to provide some help :)

**Comment by JSubelj** [comment]
Thank you very much. I edited the wiki and will fix this in the future release.

**Comment by JSubelj** [comment]
I added your USB_PRODUCT variable into the driver so it should work when installed without any modifications. If you have any questions or problems please open a new issue request or comment here (related issue). 

Have fun.
